export interface ModelDefinition {
    readonly provider: 'openai' | 'google' | 'openrouter' | 'huggingface' | 'groq' | 'cerebras' | 'local' | 'ollama';
    readonly providerModel: string;
    readonly label: string;
    readonly description: string;
    readonly providerLabel: string;
    readonly capabilities: readonly string[];
    readonly contextWindow: string;
    readonly tier: 'premium' | 'free' | 'preview' | 'local' | 'ollama';
    readonly tags: readonly string[];
    readonly requiredEnv: readonly string[];
    readonly enabledInPicker: boolean;
}

export const MODEL_REGISTRY = {
    // --- Premium / Paid ---
    'openai-gpt-5-4-mini': {
        provider: 'openai',
        providerModel: 'gpt-5.4-mini-2026-03-17',
        label: 'GPT 5.4 Mini',
        description: 'Balanced performance for everyday tasks.',
        providerLabel: 'OpenAI',
        capabilities: ['Fast', 'Reasoning'],
        contextWindow: '128k',
        tier: 'premium',
        tags: ['openai', 'gpt', 'smart', 'fast'],
        requiredEnv: ['OPENAI_API_KEY'],
        enabledInPicker: true,
    },
    'openai-gpt-5-4-nano': {
        provider: 'openai',
        providerModel: 'gpt-5.4-nano-2026-03-17',
        label: 'GPT 5.4 Nano',
        description: 'Extremely fast and cost-effective.',
        providerLabel: 'OpenAI',
        capabilities: ['Ultra Fast'],
        contextWindow: '128k',
        tier: 'premium',
        tags: ['openai', 'speed'],
        requiredEnv: ['OPENAI_API_KEY'],
        enabledInPicker: true,
    },
    'google-gemini-3-1-pro': {
        provider: 'google',
        providerModel: 'models/gemini-3.1-pro-preview',
        label: 'Gemini 3.1 Pro (Preview)',
        description: "Google's best model for large context and reasoning.",
        providerLabel: 'Google',
        capabilities: ['2M Context', 'Reasoning', 'Preview'],
        contextWindow: '2M',
        tier: 'preview',
        tags: ['google', 'gemini', 'long context', 'new'],
        requiredEnv: ['GOOGLE_GENERATIVE_AI_API_KEY'],
        enabledInPicker: true,
    },
    'google-gemini-3-5-flash': {
        provider: 'google',
        providerModel: 'models/gemini-3.5-flash',
        label: 'Gemini 3.5 Flash',
        description: 'Low latency, high throughput.',
        providerLabel: 'Google',
        capabilities: ['Fast', '1M Context'],
        contextWindow: '1M',
        tier: 'premium',
        tags: ['google', 'gemini', 'speed'],
        requiredEnv: ['GOOGLE_GENERATIVE_AI_API_KEY'],
        enabledInPicker: true,
    },
    'google-gemini-3-1-flash-lite': {
        provider: 'google',
        providerModel: 'models/gemini-3.1-flash-lite',
        label: 'Gemini 3.1 Flash Lite',
        description: 'Highly efficient lightweight model.',
        providerLabel: 'Google',
        capabilities: ['Fast', '1M Context'],
        contextWindow: '1M',
        tier: 'premium',
        tags: ['google', 'gemini', 'speed'],
        requiredEnv: ['GOOGLE_GENERATIVE_AI_API_KEY'],
        enabledInPicker: true,
    },
    'google-default': {
        provider: 'google',
        providerModel: 'models/gemini-3.5-flash',
        label: 'Gemini 3.5 Flash (Default)',
        description: 'Default build of the next generation multimodal model.',
        providerLabel: 'Google',
        capabilities: ['Preview', 'Multimodal'],
        contextWindow: '1M',
        tier: 'premium',
        tags: ['google', 'gemini', 'new', 'default'],
        requiredEnv: ['GOOGLE_GENERATIVE_AI_API_KEY'],
        enabledInPicker: false,
    },
    // --- Cerebras ---
    'cerebras-gpt-oss-120b': {
        provider: 'cerebras',
        providerModel: 'gpt-oss-120b',
        label: 'GPT-OSS 120B',
        description: 'Large scale open model.',
        providerLabel: 'Cerebras',
        capabilities: ['Large', 'Fast'],
        contextWindow: '64k',
        tier: 'premium',
        tags: ['cerebras', 'gpt', 'oss'],
        requiredEnv: ['CEREBRAS_API_KEY'],
        enabledInPicker: true,
    },
    'cerebras-llama-3-1-8b': {
        provider: 'cerebras',
        providerModel: 'llama3.1-8b',
        label: 'Llama 3.1 8B',
        description: 'Fast open source model.',
        providerLabel: 'Cerebras',
        capabilities: ['Fast'],
        contextWindow: '8k',
        tier: 'premium',
        tags: ['cerebras', 'llama', 'fast'],
        requiredEnv: ['CEREBRAS_API_KEY'],
        enabledInPicker: true,
    },
    'cerebras-qwen-3-235b': {
        provider: 'cerebras',
        providerModel: 'qwen-3-235b-a22b-instruct-2507',
        label: 'Qwen 3 235B',
        description: 'Massive Qwen model for complex tasks.',
        providerLabel: 'Cerebras',
        capabilities: ['Massive', 'Reasoning'],
        contextWindow: '64k',
        tier: 'premium',
        tags: ['cerebras', 'qwen', 'massive'],
        requiredEnv: ['CEREBRAS_API_KEY'],
        enabledInPicker: true,
    },
    'cerebras-zai-glm-4-7': {
        provider: 'cerebras',
        providerModel: 'zai-glm-4.7',
        label: 'GLM 4.7 (Zhipu)',
        description: 'GLM 4.7 model optimized for Chinese and multilingual tasks.',
        providerLabel: 'Cerebras',
        capabilities: ['Multilingual', 'Fast'],
        contextWindow: '64k',
        tier: 'premium',
        tags: ['cerebras', 'glm', 'fast'],
        requiredEnv: ['CEREBRAS_API_KEY'],
        enabledInPicker: true,
    },
    // --- Free / Community ---
    'neuman-gpt-oss-free': {
        provider: 'groq',
        providerModel: 'qwen/qwen3-32b', // server placeholder mapping
        label: 'GPT OSS 120b',
        description: 'Large open source model hosted on Groq.',
        providerLabel: 'Groq',
        capabilities: ['Fast', 'Free'],
        contextWindow: '8k',
        tier: 'free',
        tags: ['groq', 'oss', 'free'],
        requiredEnv: ['GROQ_API_KEY'],
        enabledInPicker: true,
    },
    'google-gemma-3n': {
        provider: 'openrouter',
        providerModel: 'google/gemma-3n-e2b-it:free',
        label: 'Gemma 3n',
        description: 'Efficient open model from Google.',
        providerLabel: 'Google',
        capabilities: ['Efficient', 'Free'],
        contextWindow: '8k',
        tier: 'free',
        tags: ['google', 'gemma', 'free'],
        requiredEnv: ['OPENROUTER_API_KEY'],
        enabledInPicker: true,
    },
    'google-gemma-3-27b': {
        provider: 'openrouter',
        providerModel: 'google/gemma-3-27b-it:free',
        label: 'Gemma 3 27b',
        description: 'Larger variant of Gemma 3.',
        providerLabel: 'Google',
        capabilities: ['Balanced', 'Free'],
        contextWindow: '8k',
        tier: 'free',
        tags: ['google', 'gemma', 'free'],
        requiredEnv: ['OPENROUTER_API_KEY'],
        enabledInPicker: true,
    },
    'hf-apriel-15b': {
        provider: 'huggingface',
        providerModel: 'ServiceNow-AI/Apriel-1.6-15b-Thinker:together',
        label: 'Apriel 1.6 15b',
        description: 'Experimental thinker model.',
        providerLabel: 'Hugging Face',
        capabilities: ['Experimental'],
        contextWindow: '16k',
        tier: 'free',
        tags: ['hf', 'free'],
        requiredEnv: ['HF_TOKEN'],
        enabledInPicker: true,
    },
    'hf-olmo-32b': {
        provider: 'huggingface',
        providerModel: 'allenai/Olmo-3.1-32B-Think:publicai',
        label: 'Olmo 3.1 32B',
        description: 'Fully open model by AllenAI.',
        providerLabel: 'Hugging Face',
        capabilities: ['Open Science'],
        contextWindow: '16k',
        tier: 'free',
        tags: ['hf', 'allenai', 'free'],
        requiredEnv: ['HF_TOKEN'],
        enabledInPicker: true,
    },
    'groq-compound': {
        provider: 'groq',
        providerModel: 'groq/compound',
        label: 'Groq Compound',
        description: 'Compound AI system running on Groq LPU.',
        providerLabel: 'Groq',
        capabilities: ['Compound'],
        contextWindow: '8k',
        tier: 'free',
        tags: ['groq', 'free'],
        requiredEnv: ['GROQ_API_KEY'],
        enabledInPicker: true,
    },
    'groq-qwen-3': {
        provider: 'groq',
        providerModel: 'qwen/qwen3-32b',
        label: 'Qwen 3 32B',
        description: 'General purpose Qwen model.',
        providerLabel: 'Groq',
        capabilities: ['General', 'Free'],
        contextWindow: '32k',
        tier: 'free',
        tags: ['groq', 'qwen', 'free'],
        requiredEnv: ['GROQ_API_KEY'],
        enabledInPicker: true,
    },
    'groq-llama-4-scout-17b-16e-instruct': {
        provider: 'groq',
        providerModel: 'meta-llama/llama-4-scout-17b-16e-instruct',
        label: 'Llama 4 Scout',
        description: 'Efficient Llama 4 scout model.',
        providerLabel: 'Groq',
        capabilities: ['New', 'Free'],
        contextWindow: '16k',
        tier: 'free',
        tags: ['groq', 'llama', 'free'],
        requiredEnv: ['GROQ_API_KEY'],
        enabledInPicker: true,
    },
    // --- Local / WebLLM ---
    'local-phi-3-mini': {
        provider: 'local',
        providerModel: 'local-phi-3-mini',
        label: 'Phi-3 Mini (Local)',
        description: 'Runs entirely in your browser using WebGPU.',
        providerLabel: 'Microsoft',
        capabilities: ['Local', 'Private', 'Offline'],
        contextWindow: '4k',
        tier: 'local',
        tags: ['local', 'phi', 'webgpu', 'offline'],
        requiredEnv: [],
        enabledInPicker: true,
    },
    'local-phi-2': {
        provider: 'local',
        providerModel: 'local-phi-2',
        label: 'Phi-2 (Local)',
        description: 'Smaller local model for older devices.',
        providerLabel: 'Microsoft',
        capabilities: ['Local', 'Private', 'Offline'],
        contextWindow: '2k',
        tier: 'local',
        tags: ['local', 'phi', 'webgpu', 'offline'],
        requiredEnv: [],
        enabledInPicker: true,
    },
    // --- Ollama ---
    'ollama-gemma-3-270m': {
        provider: 'ollama',
        providerModel: 'gemma3:270m',
        label: 'Gemma 3 270M (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Google',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'gemma'],
        requiredEnv: [],
        enabledInPicker: true,
    },
    'ollama-llama-3': {
        provider: 'ollama',
        providerModel: 'llama3',
        label: 'Llama 3 (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Meta',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'llama'],
        requiredEnv: [],
        enabledInPicker: false,
    },
    'ollama-mistral': {
        provider: 'ollama',
        providerModel: 'mistral',
        label: 'Mistral (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Mistral',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'mistral'],
        requiredEnv: [],
        enabledInPicker: false,
    },
    'ollama-gemma-2': {
        provider: 'ollama',
        providerModel: 'gemma2',
        label: 'Gemma 2 (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Google',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'gemma'],
        requiredEnv: [],
        enabledInPicker: false,
    },
    'ollama-phi-3': {
        provider: 'ollama',
        providerModel: 'phi3',
        label: 'Phi 3 (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Microsoft',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'phi'],
        requiredEnv: [],
        enabledInPicker: false,
    },
    'ollama-llama-3-70b': {
        provider: 'ollama',
        providerModel: 'llama3:70b',
        label: 'Llama 3 70B (Local)',
        description: 'Runs locally via Ollama.',
        providerLabel: 'Meta',
        capabilities: ['Local', 'Ollama'],
        contextWindow: '8k',
        tier: 'ollama',
        tags: ['ollama', 'local', 'llama'],
        requiredEnv: [],
        enabledInPicker: false,
    },
} as const satisfies Record<string, ModelDefinition>;

export type ModelId = keyof typeof MODEL_REGISTRY;
export const MODEL_IDS = Object.keys(MODEL_REGISTRY) as ModelId[];
export const SUPPORTED_MODEL_IDS = MODEL_IDS as unknown as [string, ...string[]];

export const DEFAULT_MODEL_ID = 'google-default' as const;

export function isModelId(value: unknown): value is ModelId {
    return typeof value === 'string' && value in MODEL_REGISTRY;
}

export function getModelDefinition(modelId: ModelId): ModelDefinition {
    return MODEL_REGISTRY[modelId];
}

export function getMissingProviderKeys(modelId: ModelId, env: Record<string, string | undefined>): string[] {
    const def = MODEL_REGISTRY[modelId];
    if (!def) return [];
    return def.requiredEnv.filter(key => !env[key]);
}

export function getMissingApiKey(modelId: string): string | null {
    if (!isModelId(modelId)) return 'INVALID_MODEL';
    const missing = getMissingProviderKeys(modelId, process.env);
    return missing.length > 0 ? missing[0] : null;
}
